### PR TITLE
Set up default values for BASE_HREF and APP_GRID_ITEMS

### PR DESCRIPTION
**Pull request by tanandy**
related to https://github.com/OpenPaaS-Suite/openpaas-front/issues/2

### CODE REVIEW

**Review by rezk2ll — APPROVED** [review]

**Review by piavgh — APPROVED** [review]
Just for understanding, where will we use the `BASE_HREF` and `APP_GRID_ITEMS` arguments?

**Comment by rezk2ll** [comment]
> Just for understanding, where will we use the `BASE_HREF` and `APP_GRID_ITEMS` arguments?

will be used when building the SPA with `webpack`.

**Comment by tanandy** [comment]
> > Just for understanding, where will we use the `BASE_HREF` and `APP_GRID_ITEMS` arguments?
> 
> will be used when building the SPA with `webpack`.

Yes thats it

**Comment by piavgh** [comment]
> > Just for understanding, where will we use the `BASE_HREF` and `APP_GRID_ITEMS` arguments?
> 
> will be used when building the SPA with `webpack`.

Do you mean that it will be available as `process.env.BASE_HREF` for this command `RUN npm run build:prod` ?

**Comment by tanandy** [comment]
> > > Just for understanding, where will we use the `BASE_HREF` and `APP_GRID_ITEMS` arguments?
> > 
> > 
> > will be used when building the SPA with `webpack`.
> 
> Do you mean that it will be available as `process.env.BASE_HREF` for this command `RUN npm run build:prod` ?

yes env.BASE_HREF

**Comment by piavgh** [comment]
got it, thanks

**Comment by tanandy** [comment]
> got it, thanks

can you review others than i can merge plz

**Pull request merged**
