### PR TITLE
#98 replace clockpicker with a time input

### PR DESCRIPTION
**Pull request by rezk2ll**
demo: https://streamable.com/667hrn

TODO:

* [ ] write tests

### CODE REVIEW

**Review by tuanlc — COMMENTED** [review]
Hey!
Can you provide screenshot, demo for new UX/UI?
No test for changes?

**Comment by rezk2ll** [comment]
> Hey!
> Can you provide screenshot, demo for new UX/UI?
> No test for changes?

i'm on it, just wanted to show you a draft with this pr

**Comment by tuanlc** [comment]
> > Hey!
> > Can you provide screenshot, demo for new UX/UI?
> > No test for changes?
> 
> i'm on it, just wanted to show you a draft with this pr

If it is not ready to merge, please convert it as a draft version

**Comment by MichaelBailly** [comment]
I did some early test and I note that you have to add the attribute `step="60"` otherwise Firefox also display the seconds .

**Comment by MichaelBailly** [comment]
Also, Safari does not support this attribute, which is a problem for us. https://caniuse.com/input-datetime . And we loose (I may be wrong) the ability to display the date either in 24h or in AM/PM.

I see lots of troubles using this type of HTML element.

**Comment by huy-ta** [comment]
Closing in faviour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/146.

**Pull request closed without merging**
