### PR TITLE
#453 added env/openpaas.js file and excluded it from the webpack bundle

### PR DESCRIPTION
**Pull request by rezk2ll**
calendar SPA console:
image

production build:
image

### CODE REVIEW

**Review by huy-ta — APPROVED** [review]

**Comment by huy-ta** [comment]
Can you please do this for all the other SPAs also? :trollface:

**Comment by alagane** [comment]
@rezk2ll So it means the `env/openpaas.js` file will not be modified by webpack but it will be bundled in `env` directory? I was wondering how to do this.

**Comment by rezk2ll** [comment]
> @rezk2ll So it means the `env/openpaas.js` file will not be modified by webpack but it will be bundled in `env` directory? I was wondering how to do this on inbox.

yes exactly @alagane

**Review by alagane — APPROVED** [review]

**Comment by alagane** [comment]
That's what I did before on inbox https://github.com/OpenPaaS-Suite/esn-frontend-inbox/commit/dde5f84c082d357b934758b33e2fb8c0b2417f5b

openpaas.js file will be used to provide authentication informations, instead of environment variables, see https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/172

**Pull request merged**
