### PR TITLE
#265 fixed the propose new time date selector not displaying starting from the end date month

### PR DESCRIPTION
**Pull request by rezk2ll**
https://user-images.githubusercontent.com/6764881/110810650-4a608480-8286-11eb-9917-485e737c8b0e.mp4

### CODE REVIEW

**Comment by huy-ta** [comment]
@rezk2ll Why is this marked as DRAFT?

**Comment by rezk2ll** [comment]
> @rezk2ll Why is this marked as DRAFT?

It introduces another bug in the full date events

**Comment by huy-ta** [comment]
> > @rezk2ll Why is this marked as DRAFT?
> 
> It introduces another bug in the full date events

Yes I've seen that. We can't remove this directive.

**Comment by rezk2ll** [comment]
> > > @rezk2ll Why is this marked as DRAFT?
> > 
> > 
> > It introduces another bug in the full date events
> 
> Yes I've seen that. We can't remove this directive.

we have to remove it, it's what is causing the bootstrap picker to not function properly.
I updated my PR and everything works fine without the directive.

**Review by renaudboyer — APPROVED** [review]

**Review by huy-ta — APPROVED** [review]

**Pull request merged**
